version: '2'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry/auth:/auth
      - ./registry/certs:/certs
      - ./registry/data:/var/lib/registry
    env_file:
      - ./registry.dist.env
      - ./registry.env
